### ISSUE TITLE
Card not displaying dropdown

### ISSUE THREAD

**Issue by Mouxy** [gadget-man/iparcelbox-card#1]
Hi!

The card is not displaying the drop down to select the device. I did try adding the deviceID and device_name without success.

![ScreenShot 2022-11-02 at 10 16 42@2x](https://user-images.githubusercontent.com/642149/199464505-4312a591-fb85-4b1b-b489-824aabaa30c5.png)

**Comment by gadget-man** [comment]
In your HA 'Devices & Services' page, do you see your iParcelBox as a discovered device?  If not, please can you check your logs when HA starts to see if there are any errors showing? You may need to turn on debugging for the iParcelBox-HA integration first (I'm assuming you've already installed that from https://github.com/gadget-man/iparcelboxHA)

**Comment by Mouxy** [comment]
The integration is ok, I can see the device and control it

![ScreenShot 2022-11-02 at 11 17 11@2x](https://user-images.githubusercontent.com/642149/199476506-12481808-e9f1-45ce-bc87-82b9c8d95b3e.png)

**Comment by gadget-man** [comment]
Strange. Your card seems to be missing the dropdown to select the device from a list.  Please can you try a full restart of HA and check the logs both during start and when you add the card to see if anything shows up?
![Screenshot 2022-11-02 at 11 27 04](https://user-images.githubusercontent.com/24406912/199479864-fa4af87d-3268-4e72-8bc2-8d34b882364c.png)

**Comment by Mouxy** [comment]
I will try a few things as I running a beta version of HA and I'll check the logs.
I installed it on another instance I have running and it works as expected so I'll close this.

Sorry for wasting your time!
